map_type: costmap

obstacle_range: 2.0
raytrace_range: 3.0

transform_tolerance: 0.2

inflation_radius: 1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
